name: Build and test
on: [push]
jobs:
  build-test:
    runs-on: macOS-10.15
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Install LLVM
      run: |
        brew install llvm
        echo "LLVM_DIR=/usr/local/opt/llvm" >> $GITHUB_ENV
    - name: Install build tools
      run: brew install ccache ninja
    - name: Prepare ccache timestamp
      id: ccache_cache_timestamp
      shell: cmake -P {0}
      run: |
        string(TIMESTAMP current_date "%Y-%m-%d-%H;%M;%S" UTC)
        message("::set-output name=timestamp::${current_date}")
    - name: Restore cache
      uses: actions/cache@v2
      with:
        path: ${{ github.workspace }}/.ccache
        key: ccache-${{ steps.ccache_cache_timestamp.outputs.timestamp }}
        restore-keys: |
          ccache-
    - name: Build mull-xctest
      run: |
        set -ex
        mkdir build
        cd build
        cmake ../ -G Ninja \
          -DCMAKE_C_COMPILER="$LLVM_DIR/bin/clang" \
          -DCMAKE_CXX_COMPILER="$LLVM_DIR/bin/clang++" \
          -DCMAKE_Swift_COMPILER="$(xcrun -f swiftc)" \
          -DPATH_TO_LLVM="$LLVM_DIR" \
          -DCMAKE_CXX_FLAGS=-fno-rtti \
          -DCMAKE_CXX_COMPILER_LAUNCHER=ccache
        ninja all
      env:
        CCACHE_DIR: ${{ github.workspace }}/.ccache
    - name: Set up Python 2.7
      uses: actions/setup-python@v2
      with:
        python-version: 2.7
    - name: Test mull-xctest
      run: |
        set -ex
        pip install lit
        cd build
        lit tests -v --path $PWD/bin
