name: Build and test
on: [push]
jobs:
  build-test:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Install LLVM
      run: |
        curl -sSfL https://github.com/llvm/llvm-project/releases/download/llvmorg-11.0.0/clang+llvm-11.0.0-x86_64-linux-gnu-ubuntu-20.04.tar.xz | tar xJf -
        export LLVM_DIR=$PWD/clang+llvm-11.0.0-x86_64-linux-gnu-ubuntu-20.04
        echo "LLVM_DIR=$LLVM_DIR" >> $GITHUB_ENV
    - name: Build mull-xctest
      run: |
        set -ex
        mkdir build
        cd build
        cmake ../ \
          -DCMAKE_C_COMPILER="$LLVM_DIR/bin/clang" \
          -DCMAKE_CXX_COMPILER="$LLVM_DIR/bin/clang++" \
          -DPATH_TO_LLVM="$LLVM_DIR" \
          -DCMAKE_CXX_FLAGS=-fno-rtti
        make all

